IMAGE_SIZE: [224, 224, 3]  # as per ResNet50V2 model
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 1
OUTPUT_VARIABLES:
  - NAME: bmi
    TYPE: linear
  - NAME: age
    TYPE: linear
  - NAME: sex
    TYPE: binary
WEIGHTS: imagenet
LEARNING_RATE: 0.01
